#!/bin/bash

#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=100G
#SBATCH --time=6:00:00
#SBATCH --partition=aa100
#SBATCH --gres=gpu:1
#SBATCH --output=logs/%j.log
#SBATCH --account=ucb277_alpine1
#SBATCH --job-name=deep
#SBATCH --mail-type=ALL
#SBATCH --mail-user="rey.koki@colorado.edu"

module purge
module load cuda/11.2
module load cudnn/8.1

source /curc/sw/anaconda3/latest
conda activate alpine

python train.py
exit 0
